#!/bin/sh

FILES=`git status -s | cut -d' ' -f3 | grep -E '\.ml$|\.mli$'`

if [ -z "${FILES}" ]; then
  exit 0;
fi 

OCAMLFORMAT=`which ocamlformat`

if [ ! -x "${OCAMLFORMAT}" ]; then
  echo "git pre-commit hook failed.. Please install ocamlformat!";
  exit 1;
fi

set -e

${OCAMLFORMAT} -i -n 3 ${FILES}

git add ${FILES}
