(lang dune 3.23)
(version 0.3.7)
(name lame)
(source (github savonet/ocaml-lame))
(license GPL-2.0-or-later)
(authors "The Savonet Team <savonet-users@lists.sourceforge.net>")
(maintainers "The Savonet Team <savonet-users@lists.sourceforge.net>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name lame)
 (synopsis "MP3 encoding library")
 (description
  "Bindings for the lame library which provides functions for encoding mp3 files")
 (allow_empty)
 (depends
  conf-lame
  conf-pkg-config
  dune-configurator)
)
