#!/bin/sh

set -e

cd /tmp/liquidsoap
eval "$(opam config env)"

# The reference is generated by running the binary, which finds the script library
# through dune-site: from the install tree, not from src/libs. An incomplete one leaves
# it documenting the builtins and nothing else, and it exits 0 either way -- the
# in-development reference lost 478 of its 2075 functions that way.
rm -rf _build/install

dune build @doc
dune build --profile release ./src/js/interactive_js.bc.js
