#!/bin/sh

set -e

cd /tmp/liquidsoap
eval "$(opam config env)"

# The reference is generated by running the binary out of the install tree, and it finds
# the script library there too, through dune-site -- not in the src/libs the rule
# declares. An incomplete tree leaves it documenting the builtins and nothing else, and
# it exits 0 either way: the in-development reference lost 478 of its 2075 functions that
# way. Build that tree explicitly rather than leaving it to whatever came before.
dune build @install

dune build @doc
dune build --profile release ./src/js/interactive_js.bc.js
