(lang dune 3.23)
(version 0.2.0)
(name lo)
(source (github savonet/ocaml-lo))
(license LGPL-2.1-or-later)
(authors "The Savonet Team <savonet-users@lists.sourceforge.net>")
(maintainers "The Savonet Team <savonet-users@lists.sourceforge.net>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name lo)
 (synopsis "Bindings for the lo library which provides functions for communicating with input controls using the OSC protocol")
 (allow_empty)
 (depends
  conf-liblo
  conf-pkg-config
  dune
  dune-configurator)
)
