---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Run the following command to set up the pre-commit git hook scripts:
# $ pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      - id: check-json
      - id: check-yaml
      - id: check-xml

      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/savonet/pre-commit-ocamlformat
    rev: d120e7d5a
    hooks:
      - id: ocamlformat

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(md|yml|yaml|json)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
        exclude: ^doc/orig/fosdem2020
