language: c

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libpcre3-dev
    - libasound2-dev
    - libpulse-dev
    - libmad0-dev
    - libtag1-dev
    - libmp3lame-dev
    - libogg-dev
    - libvorbis-dev
    - libtheora-dev
    - libfaad-dev
    - libflac-dev
    - libavutil-dev
    - libswscale-dev
    - liblo-dev
    - libmagic-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libao-dev
  - sudo apt-get install -y libgavl-dev
  - sudo apt-get install -y ladspa-sdk
  - sudo apt-get install -y frei0r-plugins-dev
  - sudo apt-get install -y libsamplerate-dev
  - sudo apt-get install -y libsoundtouch-dev
  - sudo apt-get install -y libjack-jackd2-dev libsamplerate0-dev
  - sudo apt-get install -y libspeex-dev libopus-dev libschroedinger-dev
  - sudo apt-get install -y dssi-dev
  - sudo apt-get install -y libvo-aacenc-dev

script: bash -ex .travis-ci.sh
