sudo: required
env:
  - DOCKER_TAG=debian_testing
  - DOCKER_TAG=debian_stable
  - DOCKER_TAG=debian_stretch
  - DOCKER_TAG=ubuntu_bionic
  - DOCKER_TAG=ubuntu_disco
services:
- docker
script:
- export TRAVIS_COMMIT_SHORT="$(git rev-parse --short ${TRAVIS_COMMIT})"
- docker build . --tag liquidsoap-build --no-cache --build-arg DOCKER_TAG --build-arg TRAVIS_BRANCH --build-arg TRAVIS_COMMIT --build-arg TRAVIS_COMMIT_SHORT --build-arg TRAVIS_PULL_REQUEST --build-arg TRAVIS_PULL_REQUEST_BRANCH --build-arg TRAVIS_BUILD_NUMBER -f .travis/Dockerfile
- ./.travis/get-deb.sh

deploy:
  provider: s3
  access_key_id: AKIA6KFHFXRIWW5COSJE
  secret_access_key:
    secure: hPkyQfVBfKHi/bh8JzhOtmFT4gd+ln/gV8+Kyqh0sM1/UkaVTpzaKFT+meheIGhiNMYS/zM/V0RN665GLNNo3suAXOHc3P6Tl7VS0eHbqEKNhSW4fNLqVjxYxIhBWRivTWoIXU/n2jdg8GdSXKdqxauL/bgUWpL3cV4l4SQscq4=
  bucket: deb.liquidsoap.info
  skip_cleanup: true
  local_dir: debian
  acl: public_read
  on:
    repo: savonet/liquidsoap
    all_branches: true
