#!/bin/sh
# shellcheck disable=SC2068

DIR="$(dirname "$0")"
export DIR

dune exec --display=quiet --no-print-directory --root="$DIR" src/bin/liquidsoap.exe -- --no-stdlib "$DIR/src/libs/stdlib.liq" $@
