#!/bin/sh
# shellcheck disable=SC2068

DIR="$(dirname "$0")"
export DIR

opam exec dune -- exec --display=quiet --no-print-directory --root="$DIR" src/bin/liquidsoap.exe -- --stdlib "$DIR"/src/libs/stdlib.liq "$@"
