; Aggregates the ffmpeg libraries under a single name so that
; `liquidsoap_optionals` can keep selecting on `liquidsoap_ffmpeg`.

(library
 (name liquidsoap_ffmpeg)
 (libraries
  liquidsoap_ffmpeg_base
  liquidsoap_ffmpeg_decoder
  liquidsoap_ffmpeg_encoder
  liquidsoap_ffmpeg_filter
  liquidsoap_ffmpeg_io)
 (wrapped false)
 (optional))
