(lang dune 3.23)
(version 0.2.0)
(name mem_usage)
(source (github savonet/ocaml-mem_usage))
(license MIT)
(authors "Romain Beauxis <toots@rastageeks.org>")
(maintainers "The Savonet Team <contact@liquidsoap.info>")

(generate_opam_files true)
(subst disabled)

(package
 (name mem_usage)
 (allow_empty)
 (synopsis "Cross-platform stats about memory usage")
 (depends
   (ocaml (>= 4.08)))
)
