name: "Checkout Liquidsoap"
description: "Checkout liquidsoap repository in CI container"
inputs:
  sha:
    description: "Git SHA to checkout"
    required: true
  cleanup:
    description: "Remove generated doc files before checkout"
    default: false
  use-sudo:
    description: "Run git commands as opam user via sudo"
    default: true
  reset-files:
    description: "Reset working tree to clean state after checkout"
    default: false
  clean-js:
    description: "Remove JS build artifacts"
    default: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      shell: bash
      run: |
        cd /tmp/liquidsoap-full/liquidsoap
        if [ "${{ inputs.use-sudo }}" = "true" ]; then
          RUN="sudo -u opam -E"
        else
          RUN=""
        fi
        if [ "${{ inputs.cleanup }}" = "true" ]; then
          rm -rf doc/content/build.md doc/content/install.md
        fi
        if [ "${{ inputs.clean-js }}" = "true" ]; then
          rm -rf _build/default/src/js
        fi
        $RUN git remote set-url origin https://github.com/savonet/liquidsoap.git
        $RUN git fetch origin ${{ inputs.sha }}
        $RUN git checkout ${{ inputs.sha }}
        if [ "${{ inputs.reset-files }}" = "true" ]; then
          mv .git /tmp
          rm -rf ./*
          mv /tmp/.git .
          $RUN git reset --hard
        fi
