(rule
 (alias install)
 (package ffmpeg-avutil)
 (enabled_if
  (not
   (= %{env:LIQUIDSOAP_INSTALL_NO_OPTIONAL_FAIL=false} true)))
 (action
  (with-stdin-from
   ../detect/avutil_available
   (run ../detect/detect.exe check avutil))))

(library
 (name avutil)
 (public_name ffmpeg-avutil)
 (synopsis "Bindings to ffmpeg's avutil library")
 (enabled_if
  (= %{read:../detect/avutil_available} "true"))
 (foreign_stubs
  (language c)
  (names avutil_stubs)
  (extra_deps ../detect/avutil_versions)
  (flags
   (:include ../detect/avutil_c_flags.sexp)))
 (c_library_flags
  (:include ../detect/avutil_c_library_flags.sexp))
 (public_headers
  avutil_stubs.h
  polymorphic_variant_values_stubs.h
  media_types_stubs.h)
 (libraries threads))

(rule
 (targets polymorphic_variant_values_stubs.h)
 (action
  (run ../gen_code/gen_code.exe variants)))

(rule
 (targets
  pixel_format.ml
  pixel_format_stubs.h
  pixel_format_flag.ml
  pixel_format_flag_stubs.h
  color_space.ml
  color_space_stubs.h
  color_range.ml
  color_range_stubs.h
  color_primaries.ml
  color_primaries_stubs.h
  color_trc.ml
  color_trc_stubs.h
  chroma_location.ml
  chroma_location_stubs.h
  sample_format.ml
  sample_format_stubs.h
  channel_layout.ml
  channel_layout_stubs.h
  hw_device_type.ml
  hw_device_type_stubs.h
  media_types.ml
  media_types_stubs.h
  subtitle_type.ml
  subtitle_type_stubs.h
  subtitle_flag.ml
  subtitle_flag_stubs.h)
 (deps ../detect/avutil_versions)
 (enabled_if
  (= %{read:../detect/avutil_available} "true"))
 (action
  (run
   ../gen_code/gen_code.exe
   "%{cc}"
   avutil
   %{read-lines:../detect/avutil_c_flags})))
