; Sources.
;
; The source class every operator inherits from, tracks, and the language
; values that wrap sources and clocks.

(library
 (name liquidsoap_core_source)
 (wrapped false)
 (flags
  (:standard
   -open
   Liquidsoap_lang_prelude
   -open
   Liquidsoap_lang_types
   -open
   Liquidsoap_lang_data
   -open
   Liquidsoap_lang_values
   -open
   Liquidsoap_lang_ast
   -open
   Liquidsoap_lang))
 (libraries
  dtools
  duppy
  liquidsoap-lang
  liquidsoap-lang.ast
  liquidsoap-lang.data
  liquidsoap-lang.prelude
  liquidsoap-lang.types
  liquidsoap-lang.values
  liquidsoap_core_encoder
  liquidsoap_core_media
  liquidsoap_typecheck
  liquidsoap_core_stream
  liquidsoap_core_utils
  metadata
  mm
  mm.audio
  mm.base
  mm.image
  mm.video
  re
  threads.posix
  liquidsoap_core_clock
  unix))
