(lang dune 3.23)
(version 0.2.2)
(name ladspa)
(source (github savonet/ocaml-ladspa))
(license LGPL-2.1)
(authors "The Savonet Team <savonet-users@lists.sourceforge.net>")
(maintainers "The Savonet Team <savonet-users@lists.sourceforge.net>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name ladspa)
 (synopsis "Bindings for the LADSPA API which provides audio effects")
 (allow_empty)
 (depends
  dune-configurator
  (ocaml (>= 4.08))
  conf-ladspa)
)
