(lang dune 3.23)
(version 0.1.2)
(name frei0r)
(source (github savonet/ocaml-frei0r))
(license LGPL-2.1-or-later)
(authors "The Savonet Team <savonet-users@lists.sourceforge.net>")
(maintainers "The Savonet Team <savonet-users@lists.sourceforge.net>")

(generate_opam_files true)
(subst disabled)

(package
 (name frei0r)
 (synopsis "Bindings for the frei0r API which provides video effects")
 (allow_empty)
 (depends
  conf-frei0r
  conf-pkg-config
  dune-configurator)
)
