.\"                                      Hey, EMACS: -*- nroff -*-
.TH LIQUIDSOAP 1 "July 04, 2011" "Liquidsoap 1.0.0 beta2"


.SH NAME
liquidsoap \- a multimedia streaming language
.\"
.SH SYNOPSIS
.B liquidsoap
.RI [ option ... ]
.RI [ script | expression ]
.\"
.SH DESCRIPTION
.B Liquidsoap
is a programming language for describing multimedia streaming systems.
It is very flexible, making simple things simple but giving a lot
of control for advanced uses.
.B Liquidsoap
supports audio, video and MIDI streams,
and a wide range of input/output operators
including Icecast and various soundcard APIs.
It can perform a broad range of signal processing,
combine streams in various ways, support custom transitions,
generate sound procedurally...
and all this can be assembled as you wish.
Input files can be accessed remotely, or even be synthesized on the fly
using external scripts such as speech synthesis.
Finally, interaction with a running liquidsoap instance is possible
via telnet or socket.

Liquidsoap scripts passed on the command line will be evaluated:
they shall be used to define the streaming system to be ran.
It is possible to pass multiple scripts; they will all be ran successively,
and definitions from one script can be used in subsequent ones.
A script will be read from standard input if
.B \-
is given as script filename.
Information about scripting liquidsoap is available on our website:
.B http://savonet.sf.net/

If the parameter is not a file it will be treated as an expression which will 
be executed. It is a convenient way to test simple one-line scripts. In that 
case, the default is to have log messages on standard output and to disable the 
telnet server.

.\"
.SH OPTIONS
.TP
.BI \-h " NAME"
Print the description of plugins of the given name
(operators from the scripting API,
 but also protocols, stream, file and metadata formats).
.TP
.B \-c, \-\-check
Only check the syntax of the script.
It actually does a bit more, e.g. creating the sources, which includes
checking a few URIs.
.TP
.B \-q, \-\-quiet
Do not print log messages on standard output.
.TP
.B \-v, \-\-verbose
Print log messages on standard output.
.TP
.B \-\-debug
Print debugging log messages.
.TP
.B \-d, \-\-daemon
Run in daemon mode, i.e. detach and write a PID file.
.TP
.B \-\-interactive
Launch an interactive read-eval-print loop for executing scripting
expressions.
.TP
.B \-t, \-\-enable-telnet
Enable the telnet server interface.
.TP
.B \-T, \-\-disable-telnet
Disable the telnet server interface.
.TP
.B \-u, \-\-enable-unix-socket
Enable the UNIX socket server interface.
.TP
.B \-U, \-\-disable-unix-socket
Disable the UNIX socket server interface.
.TP
.B \-
Read script on standard input.
.TP
.BI \-r " FILENAME"
Process a request: resolve it, attempt to decode it, display its metadata
and duration. This is useful to test how liquidsoap sees your files.
.TP
.B \-\-list\-plugins
Human-readable List of all protocols, operators formats, metadata resolvers, outputs.
.TP
.B \-\-list\-plugins\-xml
XML list of all protocols, operators formats, metadata resolvers, outputs.
.TP
.B \-\-no\-pervasives
Do not load pervasives script libraries
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-conf\-descr\-key
Describe a configuration key.
.TP
.B \-\-conf\-descr
Display a described table of the configuration keys.
.TP
.B \-\-conf\-dump
Dump the configuration state
.TP
.B \-p, \-\-parse-only
Parse scripts but do not type-check and run them.

.\"
.SH SEE ALSO
Our website
.B http://savonet.sf.net/
and the HTML documentation coming with your distribution of liquidsoap.
.\"
.SH AUTHOR
David Baelde for Savonet <savonet-users@lists.sourceforge.net>
