; Request protocols.
;
; Protocols registered into Request: annotate: and mpd:.

(library
 (name liquidsoap_core_protocols)
 (wrapped false)
 (libraries
  dtools
  liquidsoap_core_clock
  liquidsoap_core_encoder
  liquidsoap_core_media
  liquidsoap_core_request
  liquidsoap_core_source
  liquidsoap_core_stream
  liquidsoap_core_utils
  menhirLib
  metadata
  sedlex
  duppy.stdlib_utils
  liquidsoap_core_lang
  str
  unix))
