(lang dune 3.23)
(version 0.2.3)
(name shine)
(source (github savonet/ocaml-shine))
(license GPL-2.0)
(authors "Romain Beauxis <toots@rastageeks.org>")
(maintainers "The Savonet Team <contact@liquidsoap.info>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name shine)
 (synopsis "Fixed-point MP3 encoder")
 (description
  "shine is a super fast mp3 encoding library implemented in fixed-point arithmetic.")
 (allow_empty)
 (depends
  conf-shine
  conf-pkg-config
  dune
  dune-configurator))
