(lang dune 3.23)
(version 0.1.0)
(name jack)
(source (github savonet/ocaml-jack))
(license GPL-2.0-or-later)
(authors "The Savonet Team <savonet-users@lists.sourceforge.net>")
(maintainers "The Savonet Team <savonet-users@lists.sourceforge.net>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name jack)
 (synopsis
  "Bindings for the Jack library which provides functions for linking audio programs")
 (allow_empty)
 (depends
  conf-jack
  conf-pkg-config
  dune
  dune-configurator
  threads))
