; HTTP and the harbor server.
;
; The harbor server that input.harbor and output.harbor are built on.

(library
 (name liquidsoap_core_net)
 (wrapped false)
 (preprocess
  (pps ppx_string))
 (libraries
  curl
  dtools
  duppy
  liquidsoap_core_clock
  liquidsoap_core_encoder
  liquidsoap_core_media
  liquidsoap_core_request
  liquidsoap_core_source
  liquidsoap_core_stream
  liquidsoap_core_utils
  metadata
  mm
  mm.base
  re
  duppy.stdlib_utils
  threads.posix
  liquidsoap_core_lang
  unix))
