FROM alpine:edge

ARG APK_FILE

USER root

RUN apk add --no-cache --allow-untrusted ffmpeg python3

COPY $APK_FILE /tmp/liquidsoap.apk

RUN apk add --allow-untrusted --no-cache \
      -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
      tini /tmp/liquidsoap.apk && \
      rm -rf /tmp/liquidsoap.apk

USER liquidsoap

RUN liquidsoap --cache-stdlib

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/liquidsoap"]
