ARG BASE_IMAGE

FROM $BASE_IMAGE

USER opam

COPY . /tmp/code

WORKDIR /tmp/code

ARG CPU_CORES
ARG EXCLUDE_DEPS
ARG GITHUB_SHA

RUN /tmp/code/.github/scripts/build-no-deps.sh "$CPU_CORES" "$EXCLUDE_DEPS" "$GITHUB_SHA"

ARG RUN_NUMBER

USER root

RUN mkdir -p /tmp/$RUN_NUMBER/resources && chown opam:opam /tmp/$RUN_NUMBER/resources
