name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04]
        compiler: [4.14.2, 5.2.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build module
        uses: savonet/build-and-test-ocaml-module@main
        with:
          ocaml-compiler: ${{ matrix.compiler }}
