name: Fetch and upload s3 asset
inputs:
  filter:
    description: Asset filter
    required: true
runs:
  using: composite
  steps:
    - name: Get package name
      id: get_vars
      run: |
        echo "path=$(find ${{ github.workspace }}/${{ github.run_number }}/s3-artifacts -type f | ${{ filter }} | grep -v dbg)" >> "${GITHUB_OUTPUT}"
        echo "name=$(find ${{ github.workspace }}/${{ github.run_number }}/s3-artifacts -type f | ${{ filter }} | grep -v dbg | xargs basename)" >> "${GITHUB_OUTPUT}"
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.get_vars.outputs.name }}
        path: ${{ steps.get_vars.outputs.path }}
        if-no-files-found: error
    - name: Get debug package name
      id: get_dbg_vars
      run: |
        echo "path=$(find ${{ github.workspace }}/${{ github.run_number }}/s3-artifacts -type f | ${{ filter }} | grep dbg)" >> "${GITHUB_OUTPUT}"
        echo "name=$(find ${{ github.workspace }}/${{ github.run_number }}/s3-artifacts -type f | ${{ filter }} | grep dbg | xargs basename)" >> "${GITHUB_OUTPUT}"
    - name: Upload debug package
      uses: actions/upload-artifact@v3
      if: needs.build_details.outputs.is_fork != 'true'
      with:
        name: ${{ steps.get_dbg_vars.outputs.name }}
        path: ${{ steps.get_dbg_vars.outputs.path }}
        if-no-files-found: error
