(lang dune 3.23)
(version 0.3.0)
(name alsa)
(source (github savonet/ocaml-alsa))
(license GPL-2.0)
(authors "The Savonet Team <contact@liquidsoap.info>")
(maintainers "The Savonet Team <contact@liquidsoap.info>")

(generate_opam_files true)
(subst disabled)

(package
 (name alsa)
 (synopsis "Bindings for the ALSA library which provides functions for using soundcards")
 (allow_empty)
 (depends
  (ocaml (>= 4.02.0))
  dune-configurator)
 (conflicts
  (liquidsoap (< 1.5.0)))
)
