(* Generates dune.inc: the liquidsoap_optionals library stanza, and the pair of
   modules that (select ...) picks between for each optional dependency.

   Adding an optional dependency is one line in [deps] below, then:
     dune build @gendune --auto-promote

   Fields: the module prefix (<prefix>_option.ml is what build_config.ml
   interpolates), the dune library whose availability decides the select, the
   name to print when it is missing, and the name it is reported under in
   liquidsoap.build_config.optionals -- [None] for the ones that are not
   reported there. *)

type dep = {
  prefix : string;
  library : string;
  requires : string;
  build_config : string option;
}

let dep ?build_config ?requires prefix library =
  let requires = Option.value ~default:prefix requires in
  { prefix; library; requires; build_config }

let deps =
  [
    dep "alsa" "liquidsoap_alsa" ~build_config:"alsa";
    dep "ao" "liquidsoap_ao" ~build_config:"ao";
    dep "jack" "liquidsoap_jack" ~build_config:"jack";
    dep "camlimages" "liquidsoap_camlimages" ~build_config:"camlimages";
    dep "dssi" "liquidsoap_dssi" ~build_config:"dssi";
    dep "faad" "liquidsoap_faad" ~build_config:"faad";
    dep "fdkaac" "liquidsoap_fdkaac" ~build_config:"fdkaac";
    dep "ffmpeg" "liquidsoap_ffmpeg" ~build_config:"ffmpeg";
    dep "flac" "liquidsoap_flac" ~build_config:"flac";
    dep "ogg_flac" "liquidsoap_ogg_flac" ~requires:"ogg";
    dep "frei0r" "liquidsoap_frei0r" ~build_config:"frei0r";
    dep "gd" "liquidsoap_gd" ~build_config:"gd";
    dep "graphics" "liquidsoap_graphics" ~build_config:"graphics";
    dep "inotify" "inotify" ~build_config:"inotify";
    dep "irc" "liquidsoap_irc" ~requires:"irc-client-unix" ~build_config:"irc";
    dep "jemalloc" "liquidsoap_jemalloc";
    dep "ladspa" "liquidsoap_ladspa" ~build_config:"ladspa";
    dep "lame" "liquidsoap_lame" ~build_config:"lame";
    dep "lilv" "liquidsoap_lilv" ~build_config:"lilv";
    dep "lo" "liquidsoap_lo" ~build_config:"lo";
    dep "mad" "liquidsoap_mad" ~build_config:"mad";
    dep "memtrace" "memtrace" ~build_config:"memtrace";
    dep "ogg" "liquidsoap_ogg" ~build_config:"ogg";
    dep "opus" "liquidsoap_opus" ~build_config:"opus";
    dep "osc" "liquidsoap_osc" ~requires:"osc-unix" ~build_config:"osc";
    dep "oss" "liquidsoap_oss" ~build_config:"oss";
    dep "portaudio" "liquidsoap_portaudio" ~build_config:"portaudio";
    dep "ndi" "liquidsoap_ndi" ~requires:"ctypes-foreign";
    (* The opam package is posix-time2; the module prefix is posix_time. *)
    dep "posix_time" "liquidsoap_posix_time" ~requires:"posix-time2"
      ~build_config:"posix_time2";
    dep "prometheus" "liquidsoap_prometheus" ~build_config:"prometheus";
    dep "pulseaudio" "liquidsoap_pulseaudio" ~build_config:"pulseaudio";
    dep "samplerate" "liquidsoap_samplerate" ~build_config:"samplerate";
    dep "sdl" "liquidsoap_sdl" ~requires:"sdl-liquidsoap" ~build_config:"sdl";
    dep "shine" "liquidsoap_shine" ~build_config:"shine";
    dep "soundtouch" "liquidsoap_soundtouch" ~build_config:"soundtouch";
    dep "speex" "liquidsoap_speex" ~build_config:"speex";
    dep "srt" "liquidsoap_srt" ~build_config:"srt";
    dep "syslog" "syslog" ~build_config:"syslog";
    dep "ssl" "liquidsoap_ssl" ~build_config:"ssl";
    dep "stereotool" "liquidsoap_stereotool" ~requires:"ctypes-foreign";
    dep "sqlite3" "liquidsoap_sqlite";
    dep "theora" "liquidsoap_theora" ~build_config:"theora";
    dep "tls" "liquidsoap_tls" ~requires:"tls-liquidsoap" ~build_config:"tls";
    dep "vorbis" "liquidsoap_vorbis" ~build_config:"vorbis";
    dep "winsvc" "winsvc" ~build_config:"winsvc";
    dep "xml" "liquidsoap_xml";
    dep "yaml" "liquidsoap_yaml";
    dep "xmlplaylist" "liquidsoap_xmlplaylist" ~requires:"xmlm"
      ~build_config:"xmlplaylist";
  ]

let capitalize = String.capitalize_ascii

let () =
  print_string
    "; Generated by gen_dune.ml, do not edit.\n\
     ; Regenerate with: dune build @gendune --auto-promote\n";

  List.iter
    (fun { prefix; requires; _ } ->
      Printf.printf
        {|
(rule
 (target %s_option.enabled.ml)
 (action
  (with-stdout-to
   %%{target}
   (echo "let enabled = true\nlet detected = \"yes\"\n"))))

(rule
 (target %s_option.disabled.ml)
 (action
  (with-stdout-to
   %%{target}
   (echo "let enabled = false\nlet detected = \"no (requires %s)\"\n"))))
|}
        prefix prefix requires)
    deps;

  (* The list behind liquidsoap.build_config.optionals.*, so that the set of
     reported dependencies cannot drift from the set that is selected. *)
  Printf.printf
    {|
(rule
 (target optionals_build_config.ml)
 (action
  (with-stdout-to
   %%{target}
   (progn
    (echo "let all = [\n")
|};
  List.iter
    (fun { prefix; build_config; _ } ->
      match build_config with
        | None -> ()
        | Some name ->
            Printf.printf
              "    (echo \"  (\\\"%s\\\", %s_option.enabled);\\n\")\n" name
              (capitalize prefix))
    deps;
  print_string "    (echo \"]\\n\")))))\n";

  print_string
    {|
(library
 (name liquidsoap_optionals)
 (preprocess
  (pps ppx_string))
 (wrapped false)
 (modules
  (:standard \ gen_dune))
 (flags
  (:standard -open Liquidsoap_core))
 (libraries
  liquidsoap_core
|};
  List.iter
    (fun { prefix; library; _ } ->
      Printf.printf
        "  (select\n\
        \   %s_option.ml\n\
        \   from\n\
        \   (%s -> %s_option.enabled.ml)\n\
        \   (-> %s_option.disabled.ml))\n"
        prefix library prefix prefix)
    deps;
  print_string "  ))\n"
