
(install
 (section
  (site
   (liquidsoap libs)))
 (package liquidsoap)
 (files
    visualization.liq
resolvers.liq
externals.liq
gstreamer.liq
log.liq
utils.liq
thread.liq
source.liq
process.liq
ref.liq
fades.liq
profiler.liq
setting.liq
null.liq
math.liq
error.liq
request.liq
string.liq
deprecations.liq
audio.liq
protocols.liq
video.liq
native.liq
interactive.liq
http_codes.liq
predicate.liq
file.liq
shoutcast.liq
getter.liq
io.liq
switches.liq
sound.liq
list.liq
http.liq
metadata.liq
lastfm.liq
playlist.liq
hls.liq
main.liq
server.liq))
  