(executable
 (name detect)
 (libraries unix))

(rule
 (target all_libs_available)
 (deps
  avutil_available
  avcodec_available
  av_available
  avfilter_available
  avdevice_available
  swscale_available
  swresample_available)
 (action
  (with-stdout-to
   %{target}
   (run
    ./detect.exe
    all
    avutil
    avcodec
    av
    avfilter
    avdevice
    swscale
    swresample))))

(rule
 (targets
  avutil_available
  avutil_c_flags
  avutil_c_flags.sexp
  avutil_c_library_flags.sexp
  avutil_versions)
 (deps (universe))
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   ""
   avutil
   "libavutil >= 59.39.100, libavcodec >= 61.19.100"
   -Wall
   -Wextra)))

(rule
 (targets
  avcodec_available
  avcodec_c_flags
  avcodec_c_flags.sexp
  avcodec_c_library_flags.sexp
  avcodec_versions)
 (deps (universe) avutil_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "avutil"
   avcodec
   "libavcodec >= 61.19.100, libavutil >= 59.39.100"
   -Wall
   -Wextra)))

(rule
 (targets
  av_available
  av_c_flags
  av_c_flags.sexp
  av_c_library_flags.sexp
  av_versions)
 (deps (universe) avutil_available avcodec_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "avutil avcodec"
   av
   "libavformat >= 61.7.100, libavcodec >= 61.19.100, libavutil >= 59.39.100"
   -Wall
   -Wextra)))

(rule
 (targets
  avfilter_available
  avfilter_c_flags
  avfilter_c_flags.sexp
  avfilter_c_library_flags.sexp
  avfilter_versions)
 (deps (universe) avutil_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "avutil"
   avfilter
   "libavfilter >= 10.4.100, libavutil >= 59.39.100"
   -Wall
   -Wextra)))

(rule
 (targets
  avdevice_available
  avdevice_c_flags
  avdevice_c_flags.sexp
  avdevice_c_library_flags.sexp
  avdevice_versions)
 (deps (universe) av_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "av"
   avdevice
   "libavdevice >= 61.3.100, libavformat >= 61.7.100"
   -Wall
   -Wextra)))

(rule
 (targets
  swscale_available
  swscale_c_flags
  swscale_c_flags.sexp
  swscale_c_library_flags.sexp
  swscale_versions)
 (deps (universe) avutil_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "avutil"
   swscale
   "libswscale >= 8.3.100, libavutil >= 59.39.100"
   -Wall
   -Wextra)))

(rule
 (targets
  swresample_available
  swresample_c_flags
  swresample_c_flags.sexp
  swresample_c_library_flags.sexp
  swresample_versions)
 (deps (universe) avutil_available avcodec_available)
 (action
  (run
   ./detect.exe
   detect
   --os-type
   %{os_type}
   --context
   %{context_name}
   --profile
   %{profile}
   --requires
   "avutil avcodec"
   swresample
   "libswresample >= 5.3.100, libavutil >= 59.39.100"
   -Wall
   -Wextra)))

(rule
 (target tests.inc)
 (deps
  avutil_available
  avcodec_available
  av_available
  avfilter_available
  avdevice_available
  swscale_available
  swresample_available)
 (action
  (with-stdout-to
   %{target}
   (run
    ./detect.exe
    stanzas
    %{dep:tests.dune}
    avutil
    avcodec
    av
    avfilter
    avdevice
    swscale
    swresample))))
