; Input sources.
;
; Sources that produce data of their own: playlists, harbor input, noise,
; test patterns.

(library
 (name liquidsoap_core_sources)
 (wrapped false)
 (libraries
  dtools
  duppy
  liquidsoap_core_clock
  liquidsoap_core_encoder
  liquidsoap_core_media
  liquidsoap_core_net
  liquidsoap_core_request
  liquidsoap_core_lang
  liquidsoap_core_source
  liquidsoap_core_stream
  liquidsoap_core_utils
  metadata
  mm
  mm.audio
  mm.base
  mm.image
  mm.video
  re
  duppy.stdlib_utils
  threads.posix
  liquidsoap_core_decoders
  unix))
