(lang dune 3.23)
(version 0.1.9)
(name soundtouch)
(source (github savonet/ocaml-soundtouch))
(license LGPL-2.1)
(authors "The Savonet Team <contact@liquidsoap.info>")
(maintainers "The Savonet Team <contact@liquidsoap.info>")

(generate_opam_files true)
(subst disabled)
(use_standard_c_and_cxx_flags false)

(package
 (name soundtouch)
 (synopsis "Bindings for the soundtouch library which provides functions for changing pitch and timestretching audio data")
 (allow_empty)
 (depends
  conf-soundtouch
  conf-pkg-config
  dune
  dune-configurator)
)
