(lang dune 3.6)
(version 0.3.2)
(name metadata)
(source (github savonet/ocaml-metadata))
(license GPL-3.0-or-later)
(authors "Samuel Mimram <smimram@gmail.com>")
(maintainers "Samuel Mimram <smimram@gmail.com>")

(generate_opam_files true)

(package
 (name metadata)
 (synopsis "Read metadata from various file formats")
 (description "A pure OCaml library for reading files from various formats.")
 (depends
   (ocaml (>= 4.14.0))
 )
)
