(env
 (gcstress
  (link_flags
   (:standard -runtime-variant d))))

(executable
 (name runner)
 (modules runner)
 (libraries unix))

(rule
 (alias ffmpeg_citest)
 (deps
  ../detect/avutil_available
  ../detect/avcodec_available
  ../detect/av_available
  ../detect/avfilter_available
  ../detect/avdevice_available
  ../detect/swscale_available
  ../detect/swresample_available)
 (action
  (chdir
   ../detect
   (run
    ./detect.exe
    require
    avutil
    avcodec
    av
    avfilter
    avdevice
    swscale
    swresample))))

(dynamic_include ../detect/tests.inc)
