name: Build without optional dependencies

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      minimal_exclude_deps:
        required: true
        type: string

jobs:
  build_no_depopts:
    runs-on: depot-ubuntu-24.04-4
    container:
      image: ghcr.io/savonet/liquidsoap:ci-v2-debian_trixie-5.4.0
      options: --user opam
    env:
      HOME: /home/opam
    steps:
      - name: Checkout code
        run: |
          git clone --depth 1 https://github.com/savonet/liquidsoap.git /tmp/liquidsoap
          cd /tmp/liquidsoap
          git fetch --depth 1 origin ${{ inputs.sha }}
          git checkout ${{ inputs.sha }}
      - name: Get number of CPU cores
        uses: savonet/github-actions-cpu-cores-docker@c8384053077d8c21cca9333c6388485fc7b136e1 # v1
        id: cpu_cores
      - name: Setup opam pin
        run: |
          eval "$(opam config env)"
          opam pin add -yn liquidsoap /tmp/liquidsoap
      - name: Build
        run: |
          /tmp/liquidsoap/.github/scripts/build-posix.sh "${{ steps.cpu_cores.outputs.count }}"
        env:
          GITHUB_SHA: ${{ inputs.sha }}
          LIQ_BUILD_MIN: true
          LIQUIDSOAP_MINIMAL_EXCLUDE_DEPS: ${{ inputs.minimal_exclude_deps }}
