name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build_details:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.build_details.outputs.branch }}
      sha: ${{ steps.build_details.outputs.sha }}
      is_release: ${{ steps.build_details.outputs.is_release }}
      docker_release: ${{ steps.build_details.outputs.docker_release }}
      should_build_code: ${{ steps.build_details.outputs.should_build_code }}
      s3-artifact-basepath: ${{ steps.build_details.outputs.s3-artifact-basepath }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get build details
        run: .github/scripts/build-details.sh
        id: build_details

  export_tarball:
    runs-on: ubuntu-latest
    container:
      image: savonet/liquidsoap-ci:debian_testing_amd64
      options: --user root -v ${{ github.workspace }}/tarball:/tmp/tarball
    env:
      HOME: /home/opam
    steps:
      - name: Checkout code
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E git fetch origin $GITHUB_SHA
          sudo -u opam -E git checkout $GITHUB_SHA
      - name: Build tarball
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E ./.github/scripts/build-tarball.sh
      - name: Get filename
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E ./.github/scripts/tarball-filename.sh
        id: tarball_filename
      - name: Copy tarball
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          cp ${{ steps.tarball_filename.outputs.filename }} /tmp/tarball
      - name: Export tarball
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.tarball_filename.outputs.filename }}
          path: ${{ github.workspace }}/tarball/${{ steps.tarball_filename.outputs.filename }}
          if-no-files-found: error


  build_minimal:
    runs-on: ubuntu-latest
    needs: build_details
    if: ${{ needs.build_details.outputs.should_build_code }}
    container:
      image: savonet/liquidsoap-ci:debian_testing_amd64
      options: --user opam
    env:
      HOME: /home/opam
    steps:
      - name: Checkout code
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          git fetch origin $GITHUB_SHA
          git checkout $GITHUB_SHA
      - name: Build
        run: |
          cd /tmp/liquidsoap-full
          git pull
          cp PACKAGES.minimal PACKAGES
          eval $(opam config env) && ocamlfind query curl | xargs rm -rf
          opam info -f "depopts:" liquidsoap | grep -v osx-secure-transport | grep -v lilv | xargs opam remove --force -y
          cd liquidsoap
          ./.github/scripts/build-posix.sh
          ./src/liquidsoap --no-stdlib ./libs/stdlib.liq ./libs/deprecations.liq --check 'print("hello world")'
      - name: Build doc
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          ./.github/scripts/build-doc.sh

  build_posix:
    runs-on: ${{ matrix.runs-on }}
    needs: build_details
    if: ${{ needs.build_details.outputs.should_build_code }}
    strategy:
      fail-fast: false
      matrix:
        os: [debian_stable, debian_testing, ubuntu_groovy, ubuntu_focal, alpine]
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runs-on: ubuntu-latest
          - platform: arm64
            runs-on: self-hosted
    container:
      image: savonet/liquidsoap-ci:${{ matrix.os }}_${{ matrix.platform }}
      options: --user root --privileged --ulimit core=-1 --security-opt seccomp=unconfined -v ${{ github.workspace }}/core:/tmp/core -v ${{ github.workspace }}/debian:/tmp/debian -v ${{ github.workspace }}/alpine:/tmp/alpine
    env:
      HOME: /home/opam
    steps:
      - name: Enable core dump
        run: |
          ulimit -c unlimited
          mkdir -p /tmp/core
          chown -R opam /tmp/core
          echo '/tmp/core/core.%h.%e.%t' > /proc/sys/kernel/core_pattern
      - name: Checkout code
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E git fetch origin $GITHUB_SHA
          sudo -u opam -E git checkout $GITHUB_SHA
      - name: Build
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          # Remove after liquidsoap 2.0 release
          sudo -u opam -E opam install -y posix-time2
          sudo -u opam -E ./.github/scripts/build-posix.sh
          cp /tmp/liquidsoap-full/liquidsoap/src/liquidsoap /tmp/core
      - name: Build doc
        if: matrix.os != 'alpine'
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E ./.github/scripts/build-doc.sh
      - name: Run tests
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          sudo -u opam -E ./.github/scripts/test-posix.sh
      - name: Build debian package
        if: matrix.os != 'alpine'
        id: build_deb
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          chown -R opam /tmp/debian
          sudo -u opam -E ./.github/scripts/build-deb.sh "$GITHUB_SHA" ${{ needs.build_details.outputs.branch }} ${{ matrix.os }}
      - name: Upload debian packages artifacts
        if: matrix.os != 'alpine'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build_deb.outputs.basename }}
          path: ${{ github.workspace }}/debian
          if-no-files-found: error
      - name: Build alpine package
        if: matrix.os == 'alpine'
        id: build_apk
        run: |
          cd /tmp/liquidsoap-full/liquidsoap
          apk add alpine-sdk
          adduser opam abuild
          mkdir -p /tmp/alpine
          rm -rf /tmp/alpine/*
          chown -R opam /tmp/alpine 
          sudo -u opam -E ./.github/scripts/build-apk.sh ${{ needs.build_details.outputs.branch }} ${{ matrix.platform }}
      - name: Upload alpine packages artifacts
        if: matrix.os == 'alpine'
        uses: savonet/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE: ${{ github.workspace }}/alpine
          TARGET: ${{ needs.build_details.outputs.s3-artifact-basepath }}
      - name: Export potential core dumps
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: core-dump-${{ matrix.os }}-${{ matrix.platform }}
          path: ${{ github.workspace }}/core

  fetch_s3_artifacts:
    runs-on: ubuntu-latest
    needs: [build_details, build_posix]
    steps:
      - name: Prepare directory
        run: |
          rm -rf ${{ github.workspace }}/s3-artifacts
          mkdir -p ${{ github.workspace }}/s3-artifacts
      - name: Fetch S3 artifacts
        uses: savonet/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE: ${{ needs.build_details.outputs.s3-artifact-basepath }}
          TARGET: ${{ github.workspace }}/s3-artifacts
      - name: Get alpine amd64 package name
        id: apk_amd64
        run: |
          echo "##[set-output name=path;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep -v dbg | grep x86_64)"
          echo "##[set-output name=name;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep -v dbg | grep x86_64 | xargs basename)"
      - name: Upload alpine amd64 package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.apk_amd64.outputs.name }}
          path: ${{ steps.apk_amd64.outputs.path }}
          if-no-files-found: error
      - name: Get alpine amd64 debug package name
        id: apk_amd64_dbg
        run: |
          echo "##[set-output name=path;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep dbg | grep x86_64)"
          echo "##[set-output name=name;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep dbg | grep x86_64 | xargs basename)"
      - name: Upload alpine amd64 debug package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.apk_amd64_dbg.outputs.name }}
          path: ${{ steps.apk_amd64_dbg.outputs.path }}
          if-no-files-found: error
      - name: Get alpine arm64 package name
        id: apk_arm64
        run: |
          echo "##[set-output name=path;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep -v dbg | grep aarch64)"
          echo "##[set-output name=name;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep -v dbg | grep aarch64 | xargs basename)"
      - name: Upload alpine amd64 package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.apk_arm64.outputs.name }}
          path: ${{ steps.apk_arm64.outputs.path }}
          if-no-files-found: error
      - name: Get alpine arm64 debug package name
        id: apk_arm64_dbg
        run: |
          echo "##[set-output name=path;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep dbg | grep aarch64)"
          echo "##[set-output name=name;]$(find ${{ github.workspace }}/s3-artifacts -type f | grep 'apk$' | grep dbg | grep aarch64 | xargs basename)"
      - name: Upload alpine amd64 debug package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.apk_arm64_dbg.outputs.name }}
          path: ${{ steps.apk_arm64_dbg.outputs.path }}
          if-no-files-found: error

  build_win32:
    runs-on: ubuntu-latest
    needs: build_details
    if: ${{ needs.build_details.outputs.should_build_code }}
    strategy:
      fail-fast: false
      matrix:
        system: [x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: .github/scripts/build-win32.sh ${{ matrix.system }} ${{ needs.build_details.outputs.branch }}
        id: build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.basename }}
          path: ${{ steps.build.outputs.basename }}.zip

  update_release:
    runs-on: ubuntu-latest
    needs: [build_details, build_posix, build_win32, fetch_s3_artifacts]
    if: ${{ needs.build_details.outputs.is_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Tag commit
        uses: savonet/latest-tag@any-context
        with:
          description: Liquidsoap ${{ needs.build_details.outputs.branch }}
          tag-name: ${{ needs.build_details.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts/${{ needs.build_details.outputs.sha }}
      - name: List assets to upload
        run: echo "##[set-output name=assets;]$(find artifacts/${{ needs.build_details.outputs.sha }} -type f | xargs)"
        id: list_assets
      - name: Upload assets to release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build_details.outputs.branch }}
          files:  ${{ steps.list_assets.outputs.assets }}
          prerelease: true
          gzip: false
          allow_override: true

  build_docker:
    runs-on: ${{ matrix.runs-on }}
    needs: [build_details, build_posix]
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runs-on: ubuntu-latest
          - platform: arm64
            runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts/${{ needs.build_details.outputs.sha }}
      - name: Get debian testing package
        run: echo "##[set-output name=deb-file;]$(find artifacts/${{ needs.build_details.outputs.sha }} -type f | grep debian-testing | grep ${{ matrix.platform }} | grep -v dbgsym | grep deb)"
        id: debian_package
      - name: Get debian testing debug package
        run: echo "##[set-output name=deb-file;]$(find artifacts/${{ needs.build_details.outputs.sha }} -type f | grep debian-testing | grep ${{ matrix.platform }} | grep dbgsym | grep deb)"
        id: debian_debug_package
      - name: Build docker image
        run: .github/scripts/build-docker.sh ${{ steps.debian_package.outputs.deb-file }} ${{ steps.debian_debug_package.outputs.deb-file }} ${{ needs.build_details.outputs.branch }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ matrix.platform }}

  build_docker_alpine:
    runs-on: ${{ matrix.runs-on }}
    needs: [build_details, fetch_s3_artifacts]
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runs-on: ubuntu-latest
            alpine-arch: x86_64
          - platform: arm64
            runs-on: self-hosted
            alpine-arch: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts/${{ needs.build_details.outputs.sha }}
      - name: Get alpine package
        run: echo "##[set-output name=apk-file;]$(find artifacts/${{ needs.build_details.outputs.sha }} -type f | grep 'apk$' | grep -v dbg | grep ${{ matrix.alpine-arch }})"
        id: alpine_package
      - name: Get alpine debug package
        run: echo "##[set-output name=apk-file;]$(find artifacts/${{ needs.build_details.outputs.sha }} -type f | grep 'apk$' | grep dbg | grep ${{ matrix.alpine-arch }})"
        id: alpine_dbg_package
      - name: Build docker image
        run: .github/scripts/build-docker-alpine.sh ${{ steps.alpine_package.outputs.apk-file }} ${{ steps.alpine_dbg_package.outputs.apk-file }} ${{ needs.build_details.outputs.branch }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ matrix.platform }}

  build_docker_release:
    runs-on: ubuntu-latest
    needs: [build_details, build_docker, build_docker_alpine]
    if: ${{ needs.build_details.outputs.docker_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Push consolidated manifest
        run: .github/scripts/push-docker.sh ${{ needs.build_details.outputs.branch }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_PASSWORD }}
