name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  get_branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch_name.outputs.branch }}
      is_release: ${{ steps.branch_name.outputs.is_release }}
      docker_release: ${{ steps.branch_name.outputs.docker_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Extract branch name
        shell: bash
        run: .github/scripts/branch-name.sh
        id: branch_name

  build_posix_amd64:
    runs-on: ubuntu-latest
    needs: get_branch_name
    strategy:
      fail-fast: false
      matrix:
        os: [debian_stable, debian_testing, ubuntu_eoan, ubuntu_focal]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Compute docker tag
        run: echo "##[set-output name=name;]${{ matrix.os }}_amd64"
        id: tag
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/docker/Dockerfile.build
          platforms: linux/amd64
          push: false
          tags: savonet/liquidsoap-github-actions-build:${{ steps.tag.outputs.name }}
          build-args: |
            DOCKER_TAG=${{ steps.tag.outputs.name }}
            GITHUB_SHA
      - name: Run tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/docker/Dockerfile.test
          platforms: linux/amd64
          push: false
          build-args: |
            DOCKER_TAG=${{ steps.tag.outputs.name }}
      - name: Build deb
        id: build_deb
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/docker/Dockerfile.test
          platforms: linux/amd64
          push: false
          tags:  savonet/liquidsoap-github-actions-deb:${{ steps.tag.outputs.name }}
          build-args: |
            DOCKER_TAG=${{ steps.tag.outputs.name }}
            GITHUB_SHA
            BRANCH=${{ needs.get_branch_name.outputs.branch }}
      - name: Fetch debian package
        run: .github/scripts/get-deb.sh ${{ steps.tag.outputs.name }}
      - name: Upload debian packages artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build_deb.outputs.basename }}
          path: debian/pkgs/${{ steps.tag.outputs.name }}/${{ steps.build_deb.outputs.basename }}.deb

  build_win32:
    runs-on: ubuntu-latest
    needs: get_branch_name
    if: ${{ needs.get_branch_name.output.is_release }}
    strategy:
      fail-fast: false
      matrix:
        system: [x86, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: .github/scripts/build-win32.sh ${{ matrix.system }} ${{ needs.get_branch_name.outputs.branch }}
        id: build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.basename }}
          path: ${{ steps.build.outputs.basename }}.zip

  update_release:
    runs-on: ubuntu-latest
    needs: [get_branch_name, build_posix_amd64, build_win32]
    if: ${{ needs.get_branch_name.outputs.is_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Tag commit
        uses: savonet/latest-tag@any-context
        with:
          description: Liquidsoap ${{ needs.get_branch_name.outputs.branch }}
          tag-name: ${{ needs.get_branch_name.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: List assets to upload
        run: echo "##[set-output name=assets;]$(find artifacts -type f | xargs)"
        id: list_assets
      - name: Upload assets to release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.get_branch_name.outputs.branch }}
          files:  ${{ steps.list_assets.outputs.assets }}
          prerelease: true
          gzip: false
          allow_override: true

  build_docker_amd64:
    runs-on: ubuntu-latest
    needs: [get_branch_name, build_posix_amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Get debian testing package
        run: echo "##[set-output name=deb-file;]$(find artifacts -type f | grep debian-testing | grep amd64 | grep deb)"
        id: debian_package
      - name: Build docker image
        run: .github/scripts/build-docker.sh ${{ steps.debian_package.outputs.deb-file }} ${{ needs.get_branch_name.outputs.branch }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_PASSWORD }} amd64

  build_docker:
    runs-on: ubuntu-latest
    needs: [get_branch_name, build_docker_amd64]
    if: ${{ needs.get_branch_name.output.docker_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Push consolidated manifest
        run: .github/scripts/push-docker.sh ${{ needs.get_branch_name.outputs.branch }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_PASSWORD }}
