name: CI
on:
  pull_request:
  push:
    branches:
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [debian_stable, debian_testing, ubuntu_eoan, ubuntu_focal]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --build-arg DOCKER_TAG=${{ matrix.os }} --build-arg GITHUB_SHA -t savonet/liquidsoap-github-actions-build:${{ matrix.os }} -f .github/docker/Dockerfile.build
    - name: Run tests
      run: docker build . --build-arg DOCKER_TAG=${{ matrix.os }} --build-arg GITHUB_SHA -f .github/docker/Dockerfile.test
    - name: Build debian package
      run: docker build . --build-arg DOCKER_TAG=${{ matrix.os }} --build-arg GITHUB_SHA --build-arg GITHUB_HEAD_REF --build-arg GITHUB_RUN_NUMBER -t savonet/liquidsoap-github-actions-deb:${{ matrix.os }}  -f .github/docker/Dockerfile.deb
    - name: Fetch debian package
      run: .github/scripts/get-deb.sh ${{ matrix.os }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} debian packages
        path: debian
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: deb.liquidsoap.info
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: debian
